const express = require("express");
const session = require("express-session");
const bcrypt = require("bcryptjs");
const { db, isPostgres } = require("./db");
const multer = require("multer");
const helmet = require("helmet");
const path = require("path");
const fs = require("fs");

const app = express();
const PORT = process.env.PORT || 3000;
const ROOT = __dirname;

const UPLOAD_DIR = process.env.UPLOAD_DIR || path.join(ROOT, "uploads");

fs.mkdirSync(UPLOAD_DIR, { recursive: true });

console.log(`Database mode: ${isPostgres ? "PostgreSQL / Neon" : "SQLite"}`);

/* =========================================================
   MIDDLEWARE
========================================================= */

app.use(
  helmet({
    contentSecurityPolicy: false,
  }),
);

app.use(express.json({ limit: "2mb" }));
app.use(express.urlencoded({ extended: true }));

app.use(
  session({
    secret:
      process.env.SESSION_SECRET ||
      "CHANGE_THIS_SESSION_SECRET_BEFORE_PRODUCTION",
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      sameSite: "lax",
      secure: false,
      maxAge: 1000 * 60 * 60 * 8,
    },
  }),
);

app.use(express.static(path.join(ROOT, "public")));
app.use("/uploads", express.static(UPLOAD_DIR));

/* =========================================================
   DATABASE SCHEMA
========================================================= */

const ID_COLUMN = isPostgres
  ? "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
  : "INTEGER PRIMARY KEY AUTOINCREMENT";

async function initializeDatabase() {
  console.log("Initializing database...");

  await db.exec(`
    CREATE TABLE IF NOT EXISTS users(
      id ${ID_COLUMN},
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL CHECK(role IN ('student','teacher','admin')),
      year TEXT DEFAULT '',
      section TEXT DEFAULT '',
      department TEXT DEFAULT 'Computer Science',
      bio TEXT DEFAULT '',
      isActive INTEGER DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS courses(
      id ${ID_COLUMN},
      code TEXT UNIQUE NOT NULL,
      title TEXT NOT NULL,
      description TEXT DEFAULT '',
      credit_hours INTEGER DEFAULT 3,
      teacher_id INTEGER,
      published INTEGER DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(teacher_id)
        REFERENCES users(id)
        ON DELETE SET NULL
    );

    CREATE TABLE IF NOT EXISTS enrollments(
      id ${ID_COLUMN},
      user_id INTEGER NOT NULL,
      course_id INTEGER NOT NULL,
      progress REAL DEFAULT 0,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id,course_id),
      FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
      FOREIGN KEY(course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS materials(
      id ${ID_COLUMN},
      title TEXT NOT NULL,
      description TEXT DEFAULT '',
      type TEXT NOT NULL,
      file_url TEXT NOT NULL,
      file_size INTEGER DEFAULT 0,
      course_id INTEGER NOT NULL,
      uploaded_by INTEGER NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE,
      FOREIGN KEY(uploaded_by)
        REFERENCES users(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS videos(
      id ${ID_COLUMN},
      title TEXT NOT NULL,
      description TEXT DEFAULT '',
      url TEXT NOT NULL,
      duration TEXT DEFAULT '',
      course_id INTEGER NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS video_progress(
      id ${ID_COLUMN},
      user_id INTEGER NOT NULL,
      video_id INTEGER NOT NULL,
      completed INTEGER DEFAULT 0,
      UNIQUE(user_id,video_id),
      FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
      FOREIGN KEY(video_id)
        REFERENCES videos(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS quizzes(
      id ${ID_COLUMN},
      title TEXT NOT NULL,
      description TEXT DEFAULT '',
      course_id INTEGER NOT NULL,
      time_limit INTEGER DEFAULT 20,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS questions(
      id ${ID_COLUMN},
      quiz_id INTEGER NOT NULL,
      question TEXT NOT NULL,
      option_a TEXT NOT NULL,
      option_b TEXT NOT NULL,
      option_c TEXT NOT NULL,
      option_d TEXT NOT NULL,
      answer TEXT NOT NULL,
      FOREIGN KEY(quiz_id)
        REFERENCES quizzes(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS quiz_attempts(
      id ${ID_COLUMN},
      quiz_id INTEGER NOT NULL,
      user_id INTEGER NOT NULL,
      score REAL NOT NULL,
      answers_json TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(quiz_id)
        REFERENCES quizzes(id)
        ON DELETE CASCADE,
      FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS assignments(
      id ${ID_COLUMN},
      title TEXT NOT NULL,
      description TEXT DEFAULT '',
      deadline TEXT,
      course_id INTEGER NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS submissions(
      id ${ID_COLUMN},
      assignment_id INTEGER NOT NULL,
      user_id INTEGER NOT NULL,
      answer TEXT DEFAULT '',
      file_url TEXT DEFAULT '',
      grade REAL,
      feedback TEXT DEFAULT '',
      submitted_at TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(assignment_id,user_id),
      FOREIGN KEY(assignment_id)
        REFERENCES assignments(id)
        ON DELETE CASCADE,
      FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS discussions(
      id ${ID_COLUMN},
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      course_id INTEGER NOT NULL,
      user_id INTEGER NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE,
      FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS replies(
      id ${ID_COLUMN},
      discussion_id INTEGER NOT NULL,
      content TEXT NOT NULL,
      user_id INTEGER NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(discussion_id)
        REFERENCES discussions(id)
        ON DELETE CASCADE,
      FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS announcements(
      id ${ID_COLUMN},
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      course_id INTEGER,
      user_id INTEGER NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE,
      FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS bookmarks(
      id ${ID_COLUMN},
      user_id INTEGER NOT NULL,
      material_id INTEGER NOT NULL,
      UNIQUE(user_id,material_id),
      FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
      FOREIGN KEY(material_id)
        REFERENCES materials(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS course_notes(
      id ${ID_COLUMN},
      user_id INTEGER NOT NULL,
      course_id INTEGER NOT NULL,
      title TEXT NOT NULL DEFAULT 'My Note',
      content TEXT NOT NULL DEFAULT '',
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
      FOREIGN KEY(course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS live_classes(
      id ${ID_COLUMN},
      course_id INTEGER NOT NULL,
      title TEXT NOT NULL,
      room_name TEXT UNIQUE NOT NULL,
      host_id INTEGER NOT NULL,
      active INTEGER DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(course_id)
        REFERENCES courses(id)
        ON DELETE CASCADE,
      FOREIGN KEY(host_id)
        REFERENCES users(id)
        ON DELETE CASCADE
    );
  `);

  await migrateUsers();

  await seed();

  console.log("Database initialization complete.");
}

/* =========================================================
   DATABASE MIGRATION
========================================================= */

async function migrateUsers() {
  try {
    if (isPostgres) {
      const result = await db
        .prepare(
          `
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name='users'
          AND column_name='isactive'
      `,
        )
        .all();

      const hasColumn = result.length > 0;

      if (!hasColumn) {
        await db.exec(`
          ALTER TABLE users
          ADD COLUMN IF NOT EXISTS isActive INTEGER DEFAULT 1
        `);
      }
    } else {
      const columns = await db.prepare("PRAGMA table_info(users)").all();

      const names = columns.map((x) => x.name);

      if (!names.includes("isActive")) {
        await db.exec(
          "ALTER TABLE users ADD COLUMN isActive INTEGER DEFAULT 1",
        );
      }
    }
  } catch (error) {
    console.error("Migration warning:", error.message);
  }
}

/* =========================================================
   SEED DATA
========================================================= */

async function seed() {
  const countRow = await db.prepare("SELECT COUNT(*) AS c FROM users").get();

  const count = Number(countRow?.c || 0);

  if (count > 0) {
    console.log("Existing users found. Seed skipped.");
    return;
  }

  console.log("Creating initial demo data...");

  const hash = (password) => bcrypt.hashSync(password, 12);

  const addUser = db.prepare(`
    INSERT INTO users
    (name,email,password_hash,role,year,section)
    VALUES(?,?,?,?,?,?)
  `);

  const admin = await addUser.run(
    "System Administrator",
    "admin@werabe.edu.et",
    hash("Admin@12345"),
    "admin",
    "",
    "",
  );

  const teacher = await addUser.run(
    "CS Instructor",
    "teacher@werabe.edu.et",
    hash("Teacher@12345"),
    "teacher",
    "",
    "",
  );

  const student = await addUser.run(
    "Demo Student",
    "student@werabe.edu.et",
    hash("Student@12345"),
    "student",
    "2",
    "A",
  );

  const adminId = admin.lastInsertRowid;
  const teacherId = teacher.lastInsertRowid;
  const studentId = student.lastInsertRowid;

  const addCourse = db.prepare(`
    INSERT INTO courses
    (code,title,description,credit_hours,teacher_id)
    VALUES(?,?,?,?,?)
  `);

  const c1 = await addCourse.run(
    "CS101",
    "Programming Fundamentals",
    "Learn programming concepts, problem solving, variables, conditions, loops and functions.",
    3,
    teacherId,
  );

  const c2 = await addCourse.run(
    "CS201",
    "Data Structures",
    "Arrays, linked lists, stacks, queues, trees, graphs and algorithmic thinking.",
    3,
    teacherId,
  );

  const c3 = await addCourse.run(
    "CS203",
    "Database Systems",
    "Relational databases, SQL, normalization and database design.",
    3,
    teacherId,
  );

  const c1Id = c1.lastInsertRowid;
  const c2Id = c2.lastInsertRowid;
  const c3Id = c3.lastInsertRowid;

  const enroll = db.prepare(`
    INSERT INTO enrollments
    (user_id,course_id,progress)
    VALUES(?,?,?)
  `);

  await enroll.run(studentId, c1Id, 68);
  await enroll.run(studentId, c2Id, 42);
  await enroll.run(studentId, c3Id, 25);

  const mat = db.prepare(`
    INSERT INTO materials
    (title,description,type,file_url,file_size,course_id,uploaded_by)
    VALUES(?,?,?,?,?,?,?)
  `);

  await mat.run(
    "Programming Fundamentals - Lecture 01",
    "Introduction to programming concepts",
    "PDF",
    "https://example.com/programming-lecture-01.pdf",
    0,
    c1Id,
    teacherId,
  );

  await mat.run(
    "Data Structures - Chapter 1",
    "Introduction to data structures",
    "PPT",
    "https://example.com/data-structures.pptx",
    0,
    c2Id,
    teacherId,
  );

  const vid = db.prepare(`
    INSERT INTO videos
    (title,description,url,duration,course_id)
    VALUES(?,?,?,?,?)
  `);

  await vid.run(
    "C++ Programming Introduction",
    "Variables, data types and your first program",
    "https://www.youtube.com/watch?v=8jLOx1hD3_o",
    "18 min",
    c1Id,
  );

  await vid.run(
    "Data Structures Introduction",
    "Why data structures matter",
    "https://www.youtube.com/watch?v=RBSGKlAvoiM",
    "22 min",
    c2Id,
  );

  const q = db.prepare(`
    INSERT INTO quizzes
    (title,description,course_id,time_limit)
    VALUES(?,?,?,?)
  `);

  const quiz = await q.run(
    "Programming Fundamentals Quick Quiz",
    "Test your basic programming knowledge.",
    c1Id,
    10,
  );

  const ques = db.prepare(`
    INSERT INTO questions
    (quiz_id,question,option_a,option_b,option_c,option_d,answer)
    VALUES(?,?,?,?,?,?,?)
  `);

  await ques.run(
    quiz.lastInsertRowid,
    "Which data type stores whole numbers?",
    "int",
    "string",
    "boolean",
    "float",
    "A",
  );

  await ques.run(
    quiz.lastInsertRowid,
    "Which keyword creates a function in JavaScript?",
    "func",
    "function",
    "define",
    "method",
    "B",
  );

  const asn = db.prepare(`
    INSERT INTO assignments
    (title,description,deadline,course_id)
    VALUES(?,?,?,?)
  `);

  await asn.run(
    "C++ Functions Practice",
    "Write three small programs demonstrating functions.",
    "2026-10-20",
    c1Id,
  );

  const ann = db.prepare(`
    INSERT INTO announcements
    (title,content,course_id,user_id)
    VALUES(?,?,?,?)
  `);

  await ann.run(
    "Welcome to the Learning Hub",
    "Welcome students. Check your courses and complete the practice quiz.",
    null,
    adminId,
  );

  await ann.run(
    "Programming Fundamentals Update",
    "Lecture materials and a practice quiz are now available.",
    c1Id,
    teacherId,
  );

  console.log("Initial demo data created.");
}

/* =========================================================
   FILE UPLOAD
========================================================= */

const upload = multer({
  storage: multer.diskStorage({
    destination: (_req, _file, cb) => cb(null, UPLOAD_DIR),

    filename: (_req, file, cb) =>
      cb(
        null,
        Date.now() + "-" + file.originalname.replace(/[^a-zA-Z0-9._-]/g, "_"),
      ),
  }),

  limits: {
    fileSize: 10 * 1024 * 1024,
  },

  fileFilter: (_req, file, cb) => {
    const allowed = /\.(pdf|ppt|pptx|doc|docx|zip|txt|jpg|jpeg|png)$/i.test(
      file.originalname,
    );

    cb(allowed ? null : new Error("Unsupported file type"), allowed);
  },
});

const videoUpload = multer({
  storage: multer.diskStorage({
    destination: (_req, _file, cb) => cb(null, UPLOAD_DIR),

    filename: (_req, file, cb) =>
      cb(
        null,
        "video-" +
          Date.now() +
          "-" +
          file.originalname.replace(/[^a-zA-Z0-9._-]/g, "_"),
      ),
  }),

  limits: {
    fileSize: 200 * 1024 * 1024,
  },

  fileFilter: (_req, file, cb) => {
    const allowed = /\.(mp4|webm|ogg|mov|m4v)$/i.test(file.originalname);

    cb(
      allowed
        ? null
        : new Error("Unsupported video type. Use MP4, WebM, OGG, MOV or M4V."),
      allowed,
    );
  },
});

/* =========================================================
   AUTH HELPERS
========================================================= */

const auth = (req, res, next) => {
  if (!req.session.user) {
    return res.status(401).json({ error: "Login required" });
  }

  next();
};

const role =
  (...roles) =>
  (req, res, next) => {
    if (!req.session.user || !roles.includes(req.session.user.role)) {
      return res.status(403).json({ error: "Permission denied" });
    }

    next();
  };

const user = (req) => req.session.user;

/* =========================================================
   AUTH ROUTES
========================================================= */

app.post("/api/auth/register", async (req, res) => {
  try {
    const { name, email, password, year, section } = req.body;

    if (!name || !email || !password || password.length < 8) {
      return res.status(400).json({
        error:
          "Name, email and a password of at least 8 characters are required",
      });
    }

    const cleanName = name.trim();
    const cleanEmail = email.toLowerCase().trim();

    const result = await db
      .prepare(
        `
          INSERT INTO users
          (name,email,password_hash,role,year,section)
          VALUES(?,?,?,?,?,?)
        `,
      )
      .run(
        cleanName,
        cleanEmail,
        bcrypt.hashSync(password, 12),
        "student",
        year || "",
        section || "",
      );

    req.session.user = {
      id: result.lastInsertRowid,
      name: cleanName,
      email: cleanEmail,
      role: "student",
    };

    res.json({
      user: req.session.user,
    });
  } catch (error) {
    console.error(error);

    res.status(400).json({
      error: "Email is already registered",
    });
  }
});

app.post("/api/auth/login", async (req, res) => {
  try {
    const email = (req.body.email || "").toLowerCase().trim();

    const u = await db.prepare("SELECT * FROM users WHERE email=?").get(email);

    if (
      !u ||
      !u.isActive ||
      !bcrypt.compareSync(req.body.password || "", u.password_hash)
    ) {
      return res.status(401).json({
        error: "Invalid email or password",
      });
    }

    req.session.user = {
      id: u.id,
      name: u.name,
      email: u.email,
      role: u.role,
      year: u.year,
      section: u.section,
    };

    res.json({
      user: req.session.user,
    });
  } catch (error) {
    console.error(error);

    res.status(500).json({
      error: "Login failed",
    });
  }
});

app.post("/api/auth/logout", (req, res) => {
  req.session.destroy(() => res.json({ ok: true }));
});

app.post("/api/auth/change-password", auth, async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;

    if (!currentPassword || !newPassword || newPassword.length < 8) {
      return res.status(400).json({
        error:
          "Current password and a new password of at least 8 characters are required",
      });
    }

    const row = await db
      .prepare("SELECT password_hash FROM users WHERE id=?")
      .get(user(req).id);

    if (!row || !bcrypt.compareSync(currentPassword, row.password_hash)) {
      return res.status(400).json({
        error: "Current password is incorrect",
      });
    }

    await db
      .prepare("UPDATE users SET password_hash=? WHERE id=?")
      .run(bcrypt.hashSync(newPassword, 12), user(req).id);

    res.json({ ok: true });
  } catch (error) {
    console.error(error);

    res.status(500).json({
      error: "Could not change password",
    });
  }
});

/* =========================================================
   HEALTH
========================================================= */

app.get("/api/health", async (_req, res) => {
  try {
    await db.prepare("SELECT 1 AS test").get();

    res.json({
      ok: true,
      app: "Werabe CS Learning Hub",

      database: {
        mode: isPostgres ? "PostgreSQL / Neon" : "SQLite",
        connected: true,
      },

      storage: {
        uploads: UPLOAD_DIR,
        persistentDatabase: isPostgres,
      },
    });
  } catch (error) {
    res.status(500).json({
      ok: false,
      error: error.message,
    });
  }
});

/* =========================================================
   CURRENT USER
========================================================= */

app.get("/api/auth/me", (req, res) =>
  res.json({
    user: user(req) || null,
  }),
);

/* =========================================================
   DASHBOARD
========================================================= */

app.get("/api/dashboard", auth, async (req, res) => {
  try {
    const uid = user(req).id;

    const courses = await db
      .prepare(
        `
          SELECT
            c.*,
            e.progress
          FROM courses c
          JOIN enrollments e
            ON e.course_id=c.id
          WHERE e.user_id=?
          ORDER BY c.title
        `,
      )
      .all(uid);

    const announcements = await db
      .prepare(
        `
          SELECT
            a.*,
            c.title course_title,
            u.name author
          FROM announcements a
          LEFT JOIN courses c
            ON c.id=a.course_id
          JOIN users u
            ON u.id=a.user_id
          ORDER BY a.created_at DESC
          LIMIT 6
        `,
      )
      .all();

    const quizzes = await db
      .prepare(
        `
          SELECT
            q.*,
            c.title course_title
          FROM quizzes q
          JOIN courses c
            ON c.id=q.course_id
          ORDER BY q.created_at DESC
          LIMIT 5
        `,
      )
      .all();

    const assignments = await db
      .prepare(
        `
          SELECT
            a.*,
            c.title course_title
          FROM assignments a
          JOIN courses c
            ON c.id=a.course_id
          ORDER BY a.deadline
          LIMIT 5
        `,
      )
      .all();

    const materialsCount = await db
      .prepare("SELECT COUNT(*) AS c FROM materials")
      .get();

    const videosCount = await db
      .prepare("SELECT COUNT(*) AS c FROM videos")
      .get();

    const discussionsCount = await db
      .prepare("SELECT COUNT(*) AS c FROM discussions")
      .get();

    const stats = {
      enrolled: courses.length,
      materials: Number(materialsCount.c),
      videos: Number(videosCount.c),
      discussions: Number(discussionsCount.c),
    };

    res.json({
      courses,
      announcements,
      quizzes,
      assignments,
      stats,
    });
  } catch (error) {
    console.error(error);

    res.status(500).json({
      error: "Could not load dashboard",
    });
  }
});

/* =========================================================
   COURSES
========================================================= */

app.get("/api/courses", async (req, res) => {
  try {
    const courses = await db
      .prepare(
        `
          SELECT
            c.*,
            u.name teacher,
            (
              SELECT COUNT(*)
              FROM enrollments e
              WHERE e.course_id=c.id
            ) students
          FROM courses c
          LEFT JOIN users u
            ON u.id=c.teacher_id
          WHERE c.published=1
          ORDER BY c.title
        `,
      )
      .all();

    res.json(courses);
  } catch (error) {
    console.error(error);

    res.status(500).json({
      error: "Could not load courses",
    });
  }
});

app.get("/api/courses/:id", auth, async (req, res) => {
  try {
    const c = await db
      .prepare(
        `
          SELECT
            c.*,
            u.name teacher
          FROM courses c
          LEFT JOIN users u
            ON u.id=c.teacher_id
          WHERE c.id=?
        `,
      )
      .get(req.params.id);

    if (!c) {
      return res.status(404).json({
        error: "Course not found",
      });
    }

    const materials = await db
      .prepare(
        `
          SELECT
            m.*,
            u.name uploader
          FROM materials m
          JOIN users u
            ON u.id=m.uploaded_by
          WHERE m.course_id=?
          ORDER BY m.created_at DESC
        `,
      )
      .all(req.params.id);

    const videos = await db
      .prepare(
        `
          SELECT *
          FROM videos
          WHERE course_id=?
          ORDER BY created_at DESC
        `,
      )
      .all(req.params.id);

    const quizzes = await db
      .prepare(
        `
          SELECT *
          FROM quizzes
          WHERE course_id=?
          ORDER BY created_at DESC
        `,
      )
      .all(req.params.id);

    const assignments = await db
      .prepare(
        `
          SELECT *
          FROM assignments
          WHERE course_id=?
          ORDER BY deadline
        `,
      )
      .all(req.params.id);

    const discussions = await db
      .prepare(
        `
          SELECT
            d.*,
            u.name author,
            (
              SELECT COUNT(*)
              FROM replies r
              WHERE r.discussion_id=d.id
            ) replies
          FROM discussions d
          JOIN users u
            ON u.id=d.user_id
          WHERE d.course_id=?
          ORDER BY d.created_at DESC
        `,
      )
      .all(req.params.id);

    const enrollment = await db
      .prepare(
        `
          SELECT *
          FROM enrollments
          WHERE user_id=?
            AND course_id=?
        `,
      )
      .get(user(req).id, req.params.id);

    const notes = await db
      .prepare(
        `
          SELECT
            id,
            title,
            content,
            updated_at
          FROM course_notes
          WHERE user_id=?
            AND course_id=?
          ORDER BY updated_at DESC
        `,
      )
      .all(user(req).id, req.params.id);

    const liveClasses = await db
      .prepare(
        `
          SELECT
            l.*,
            u.name host_name
          FROM live_classes l
          JOIN users u
            ON u.id=l.host_id
          WHERE l.course_id=?
            AND l.active=1
          ORDER BY l.created_at DESC
        `,
      )
      .all(req.params.id);

    res.json({
      course: c,
      materials,
      videos,
      quizzes,
      assignments,
      discussions,
      enrollment,
      notes,
      liveClasses,
    });
  } catch (error) {
    console.error(error);

    res.status(500).json({
      error: "Could not load course",
    });
  }
});

app.post("/api/courses/:id/enroll", role("student"), async (req, res) => {
  try {
    await db
      .prepare(
        `
          INSERT INTO enrollments
          (user_id,course_id)
          VALUES(?,?)
        `,
      )
      .run(user(req).id, req.params.id);

    res.json({ ok: true });
  } catch (error) {
    res.status(400).json({
      error: "Already enrolled",
    });
  }
});

app.post("/api/courses", role("teacher", "admin"), async (req, res) => {
  try {
    const { code, title, description, creditHours = 3, teacherId } = req.body;

    if (!code || !title) {
      return res.status(400).json({
        error: "Code and title required",
      });
    }

    const tid = user(req).role === "teacher" ? user(req).id : teacherId || null;

    const result = await db
      .prepare(
        `
          INSERT INTO courses
          (code,title,description,credit_hours,teacher_id)
          VALUES(?,?,?,?,?)
        `,
      )
      .run(code, title, description || "", creditHours, tid);

    res.json({
      id: result.lastInsertRowid,
    });
  } catch (error) {
    console.error(error);

    res.status(400).json({
      error: "Course code already exists",
    });
  }
});

/* =========================================================
   LIVE CLASSES
========================================================= */

app.post(
  "/api/courses/:id/live-classes",
  role("teacher", "admin"),
  async (req, res) => {
    try {
      const { title = "Live Class" } = req.body;

      const course = await db
        .prepare("SELECT id FROM courses WHERE id=?")
        .get(req.params.id);

      if (!course) {
        return res.status(404).json({
          error: "Course not found",
        });
      }

      const safe = String(title).trim() || "Live Class";

      const room =
        "WerabeCS-" +
        req.params.id +
        "-" +
        Date.now() +
        "-" +
        Math.random().toString(36).slice(2, 9);

      const result = await db
        .prepare(
          `
          INSERT INTO live_classes
          (course_id,title,room_name,host_id)
          VALUES(?,?,?,?)
        `,
        )
        .run(req.params.id, safe, room, user(req).id);

      res.json({
        id: result.lastInsertRowid,
        roomName: room,
      });
    } catch (error) {
      console.error(error);

      res.status(500).json({
        error: "Could not create live class",
      });
    }
  },
);

app.post(
  "/api/live-classes/:id/end",
  role("teacher", "admin"),
  async (req, res) => {
    await db
      .prepare("UPDATE live_classes SET active=0 WHERE id=?")
      .run(req.params.id);

    res.json({ ok: true });
  },
);

app.get("/api/courses/:id/live-classes", auth, async (req, res) => {
  const rows = await db
    .prepare(
      `
        SELECT
          l.*,
          u.name host_name
        FROM live_classes l
        JOIN users u
          ON u.id=l.host_id
        WHERE l.course_id=?
          AND l.active=1
        ORDER BY l.created_at DESC
      `,
    )
    .all(req.params.id);

  res.json(rows);
});

/* =========================================================
   NOTES
========================================================= */

app.get("/api/courses/:id/notes", role("student"), async (req, res) => {
  const rows = await db
    .prepare(
      `
        SELECT
          id,
          title,
          content,
          updated_at
        FROM course_notes
        WHERE user_id=?
          AND course_id=?
        ORDER BY updated_at DESC
      `,
    )
    .all(user(req).id, req.params.id);

  res.json(rows);
});

app.post("/api/courses/:id/notes", role("student"), async (req, res) => {
  const title = String(req.body.title || "My Note").trim();

  const content = String(req.body.content || "").trim();

  if (!content) {
    return res.status(400).json({
      error: "Note content is required",
    });
  }

  const result = await db
    .prepare(
      `
        INSERT INTO course_notes
        (user_id,course_id,title,content,updated_at)
        VALUES(?,?,?,?,CURRENT_TIMESTAMP)
      `,
    )
    .run(user(req).id, req.params.id, title || "My Note", content);

  res.json({
    id: result.lastInsertRowid,
  });
});

app.put("/api/notes/:id", role("student"), async (req, res) => {
  const title = String(req.body.title || "My Note").trim();

  const content = String(req.body.content || "").trim();

  const result = await db
    .prepare(
      `
        UPDATE course_notes
        SET
          title=?,
          content=?,
          updated_at=CURRENT_TIMESTAMP
        WHERE id=?
          AND user_id=?
      `,
    )
    .run(title || "My Note", content, req.params.id, user(req).id);

  if (!result.changes) {
    return res.status(404).json({
      error: "Note not found",
    });
  }

  res.json({ ok: true });
});

app.delete("/api/notes/:id", role("student"), async (req, res) => {
  const result = await db
    .prepare(
      `
        DELETE FROM course_notes
        WHERE id=?
          AND user_id=?
      `,
    )
    .run(req.params.id, user(req).id);

  if (!result.changes) {
    return res.status(404).json({
      error: "Note not found",
    });
  }

  res.json({ ok: true });
});

/* =========================================================
   MATERIALS
========================================================= */

app.get("/api/materials", auth, async (req, res) => {
  try {
    const q = (req.query.q || "").trim();

    let rows;

    if (q) {
      rows = await db
        .prepare(
          `
            SELECT
              m.*,
              c.title course_title
            FROM materials m
            JOIN courses c
              ON c.id=m.course_id
            WHERE m.title LIKE ?
               OR m.description LIKE ?
            ORDER BY m.created_at DESC
          `,
        )
        .all("%" + q + "%", "%" + q + "%");
    } else {
      rows = await db
        .prepare(
          `
            SELECT
              m.*,
              c.title course_title
            FROM materials m
            JOIN courses c
              ON c.id=m.course_id
            ORDER BY m.created_at DESC
          `,
        )
        .all();
    }

    res.json(rows);
  } catch (error) {
    console.error(error);

    res.status(500).json({
      error: "Could not load materials",
    });
  }
});

app.post(
  "/api/courses/:id/materials",
  role("teacher", "admin"),
  upload.single("file"),
  async (req, res) => {
    try {
      if (!req.file) {
        return res.status(400).json({
          error: "File required",
        });
      }

      const type = path.extname(req.file.originalname).slice(1).toUpperCase();

      const url = "/uploads/" + req.file.filename;

      const result = await db
        .prepare(
          `
          INSERT INTO materials
          (title,description,type,file_url,file_size,course_id,uploaded_by)
          VALUES(?,?,?,?,?,?,?)
        `,
        )
        .run(
          req.body.title || req.file.originalname,
          req.body.description || "",
          type,
          url,
          req.file.size,
          req.params.id,
          user(req).id,
        );

      res.json({
        id: result.lastInsertRowid,
        url,
      });
    } catch (error) {
      console.error(error);

      res.status(500).json({
        error: "Could not upload material",
      });
    }
  },
);

/* =========================================================
   VIDEOS
========================================================= */

app.post(
  "/api/courses/:id/videos",
  role("teacher", "admin"),
  async (req, res) => {
    try {
      const { title, description, url, duration = "" } = req.body;

      if (!title || !url) {
        return res.status(400).json({
          error: "Title and URL required",
        });
      }

      const result = await db
        .prepare(
          `
          INSERT INTO videos
          (title,description,url,duration,course_id)
          VALUES(?,?,?,?,?)
        `,
        )
        .run(title, description || "", url, duration, req.params.id);

      res.json({
        id: result.lastInsertRowid,
      });
    } catch (error) {
      console.error(error);

      res.status(500).json({
        error: "Could not add video",
      });
    }
  },
);

app.post(
  "/api/courses/:id/videos/upload",
  role("teacher", "admin"),
  videoUpload.single("video"),
  async (req, res) => {
    try {
      if (!req.file) {
        return res.status(400).json({
          error: "Video file required",
        });
      }

      const title = (req.body.title || req.file.originalname).trim();

      if (!title) {
        return res.status(400).json({
          error: "Video title required",
        });
      }

      const url = "/uploads/" + req.file.filename;

      const result = await db
        .prepare(
          `
          INSERT INTO videos
          (title,description,url,duration,course_id)
          VALUES(?,?,?,?,?)
        `,
        )
        .run(
          title,
          req.body.description || "",
          url,
          req.body.duration || "",
          req.params.id,
        );

      res.json({
        id: result.lastInsertRowid,
        url,
      });
    } catch (error) {
      console.error(error);

      res.status(500).json({
        error: "Could not upload video",
      });
    }
  },
);

app.post("/api/videos/:id/complete", role("student"), async (req, res) => {
  await db
    .prepare(
      `
        INSERT INTO video_progress
        (user_id,video_id,completed)
        VALUES(?,?,1)
        ON CONFLICT(user_id,video_id)
        DO UPDATE SET completed=1
      `,
    )
    .run(user(req).id, req.params.id);

  res.json({ ok: true });
});

/* =========================================================
   QUIZZES
========================================================= */

app.post(
  "/api/courses/:id/quizzes",
  role("teacher", "admin"),
  async (req, res) => {
    try {
      const { title, description, timeLimit = 20, questions = [] } = req.body;

      const quiz = await db
        .prepare(
          `
          INSERT INTO quizzes
          (title,description,course_id,time_limit)
          VALUES(?,?,?,?)
        `,
        )
        .run(title, description || "", req.params.id, timeLimit);

      const addQuestion = db.prepare(`
          INSERT INTO questions
          (quiz_id,question,option_a,option_b,option_c,option_d,answer)
          VALUES(?,?,?,?,?,?,?)
        `);

      for (const x of questions) {
        await addQuestion.run(
          quiz.lastInsertRowid,
          x.question,
          x.a,
          x.b,
          x.c,
          x.d,
          x.answer,
        );
      }

      res.json({
        id: quiz.lastInsertRowid,
      });
    } catch (error) {
      console.error(error);

      res.status(500).json({
        error: "Could not create quiz",
      });
    }
  },
);

app.get("/api/quizzes/:id", auth, async (req, res) => {
  const quiz = await db
    .prepare(
      `
        SELECT
          q.*,
          c.title course_title
        FROM quizzes q
        JOIN courses c
          ON c.id=q.course_id
        WHERE q.id=?
      `,
    )
    .get(req.params.id);

  if (!quiz) {
    return res.status(404).json({
      error: "Quiz not found",
    });
  }

  const questions = await db
    .prepare(
      `
        SELECT
          id,
          question,
          option_a a,
          option_b b,
          option_c c,
          option_d d
        FROM questions
        WHERE quiz_id=?
      `,
    )
    .all(req.params.id);

  res.json({
    quiz,
    questions,
  });
});

app.post("/api/quizzes/:id/submit", role("student"), async (req, res) => {
  const questions = await db
    .prepare(
      `
        SELECT id,answer
        FROM questions
        WHERE quiz_id=?
      `,
    )
    .all(req.params.id);

  const answers = req.body.answers || {};

  let correct = 0;

  for (const question of questions) {
    if (answers[question.id] === question.answer) {
      correct++;
    }
  }

  const score = questions.length
    ? Math.round((correct / questions.length) * 100)
    : 0;

  await db
    .prepare(
      `
        INSERT INTO quiz_attempts
        (quiz_id,user_id,score,answers_json)
        VALUES(?,?,?,?)
      `,
    )
    .run(req.params.id, user(req).id, score, JSON.stringify(answers));

  res.json({
    score,
    correct,
    total: questions.length,
  });
});

/* =========================================================
   ASSIGNMENTS
========================================================= */

app.post(
  "/api/courses/:id/assignments",
  role("teacher", "admin"),
  async (req, res) => {
    try {
      const { title, description, deadline } = req.body;

      const result = await db
        .prepare(
          `
          INSERT INTO assignments
          (title,description,deadline,course_id)
          VALUES(?,?,?,?)
        `,
        )
        .run(title, description || "", deadline || null, req.params.id);

      res.json({
        id: result.lastInsertRowid,
      });
    } catch (error) {
      console.error(error);

      res.status(500).json({
        error: "Could not create assignment",
      });
    }
  },
);

app.post("/api/assignments/:id/submit", role("student"), async (req, res) => {
  try {
    await db
      .prepare(
        `
          INSERT INTO submissions
          (assignment_id,user_id,answer)
          VALUES(?,?,?)
          ON CONFLICT(assignment_id,user_id)
          DO UPDATE SET
            answer=excluded.answer,
            submitted_at=CURRENT_TIMESTAMP
        `,
      )
      .run(req.params.id, user(req).id, req.body.answer || "");

    res.json({ ok: true });
  } catch (error) {
    console.error(error);

    res.status(400).json({
      error: "Could not submit",
    });
  }
});

/* =========================================================
   DISCUSSIONS
========================================================= */

app.get("/api/discussions/:id", auth, async (req, res) => {
  const discussion = await db
    .prepare(
      `
        SELECT
          d.*,
          u.name author,
          c.title course_title
        FROM discussions d
        JOIN users u
          ON u.id=d.user_id
        JOIN courses c
          ON c.id=d.course_id
        WHERE d.id=?
      `,
    )
    .get(req.params.id);

  if (!discussion) {
    return res.status(404).json({
      error: "Discussion not found",
    });
  }

  const replies = await db
    .prepare(
      `
        SELECT
          r.*,
          u.name author
        FROM replies r
        JOIN users u
          ON u.id=r.user_id
        WHERE r.discussion_id=?
        ORDER BY r.created_at
      `,
    )
    .all(req.params.id);

  res.json({
    discussion,
    replies,
  });
});

app.post("/api/courses/:id/discussions", auth, async (req, res) => {
  const { title, content } = req.body;

  if (!title || !content) {
    return res.status(400).json({
      error: "Title and content required",
    });
  }

  const result = await db
    .prepare(
      `
        INSERT INTO discussions
        (title,content,course_id,user_id)
        VALUES(?,?,?,?)
      `,
    )
    .run(title, content, req.params.id, user(req).id);

  res.json({
    id: result.lastInsertRowid,
  });
});

app.post("/api/discussions/:id/replies", auth, async (req, res) => {
  const result = await db
    .prepare(
      `
        INSERT INTO replies
        (discussion_id,content,user_id)
        VALUES(?,?,?)
      `,
    )
    .run(req.params.id, req.body.content, user(req).id);

  res.json({
    id: result.lastInsertRowid,
  });
});

/* =========================================================
   ANNOUNCEMENTS
========================================================= */

app.get("/api/announcements", auth, async (req, res) => {
  const rows = await db
    .prepare(
      `
        SELECT
          a.*,
          c.title course_title,
          u.name author
        FROM announcements a
        LEFT JOIN courses c
          ON c.id=a.course_id
        JOIN users u
          ON u.id=a.user_id
        ORDER BY a.created_at DESC
      `,
    )
    .all();

  res.json(rows);
});

app.post("/api/announcements", role("teacher", "admin"), async (req, res) => {
  const result = await db
    .prepare(
      `
        INSERT INTO announcements
        (title,content,course_id,user_id)
        VALUES(?,?,?,?)
      `,
    )
    .run(
      req.body.title,
      req.body.content,
      req.body.courseId || null,
      user(req).id,
    );

  res.json({
    id: result.lastInsertRowid,
  });
});

/* =========================================================
   BOOKMARKS
========================================================= */

app.get("/api/bookmarks", role("student"), async (req, res) => {
  const rows = await db
    .prepare(
      `
        SELECT
          b.id,
          m.*,
          c.title course_title
        FROM bookmarks b
        JOIN materials m
          ON m.id=b.material_id
        JOIN courses c
          ON c.id=m.course_id
        WHERE b.user_id=?
        ORDER BY b.id DESC
      `,
    )
    .all(user(req).id);

  res.json(rows);
});

app.post("/api/bookmarks/:materialId", role("student"), async (req, res) => {
  try {
    await db
      .prepare(
        `
          INSERT INTO bookmarks
          (user_id,material_id)
          VALUES(?,?)
        `,
      )
      .run(user(req).id, req.params.materialId);

    res.json({ ok: true });
  } catch (error) {
    await db
      .prepare(
        `
          DELETE FROM bookmarks
          WHERE user_id=?
            AND material_id=?
        `,
      )
      .run(user(req).id, req.params.materialId);

    res.json({
      ok: true,
      removed: true,
    });
  }
});

/* =========================================================
   ADMIN
========================================================= */

app.get("/api/admin/stats", role("admin"), async (req, res) => {
  const count = async (table) => {
    const row = await db.prepare("SELECT COUNT(*) AS c FROM " + table).get();

    return Number(row.c);
  };

  const students = await db
    .prepare(
      `
        SELECT COUNT(*) AS c
        FROM users
        WHERE role='student'
      `,
    )
    .get();

  const teachers = await db
    .prepare(
      `
        SELECT COUNT(*) AS c
        FROM users
        WHERE role='teacher'
      `,
    )
    .get();

  res.json({
    users: await count("users"),
    students: Number(students.c),
    teachers: Number(teachers.c),
    courses: await count("courses"),
    materials: await count("materials"),
    videos: await count("videos"),
    quizzes: await count("quizzes"),
    discussions: await count("discussions"),
    assignments: await count("assignments"),
  });
});

app.get("/api/users", role("admin"), async (req, res) => {
  const rows = await db
    .prepare(
      `
        SELECT
          id,
          name,
          email,
          role,
          year,
          section,
          isActive,
          created_at
        FROM users
        ORDER BY created_at DESC
      `,
    )
    .all();

  res.json(rows);
});

app.patch("/api/users/:id/status", role("admin"), async (req, res) => {
  await db
    .prepare(
      `
        UPDATE users
        SET isActive=?
        WHERE id=?
      `,
    )
    .run(req.body.isActive ? 1 : 0, req.params.id);

  res.json({
    ok: true,
  });
});

/* =========================================================
   ERROR HANDLER
========================================================= */

app.use((err, req, res, next) => {
  console.error(err);

  res.status(400).json({
    error: err.message || "Request failed",
  });
});

/* =========================================================
   FRONTEND FALLBACK
========================================================= */

app.use((req, res, next) => {
  if (req.method !== "GET") {
    return next();
  }

  res.sendFile(path.join(ROOT, "public", "index.html"));
});

/* =========================================================
   START SERVER
========================================================= */

async function startServer() {
  try {
    await initializeDatabase();

    app.listen(PORT, () => {
      console.log(`Werabe Learning Hub running at http://localhost:${PORT}`);

      console.log(`Database: ${isPostgres ? "PostgreSQL / Neon" : "SQLite"}`);
    });
  } catch (error) {
    console.error("SERVER STARTUP FAILED:");
    console.error(error);

    process.exit(1);
  }
}

startServer();
